### ISSUE TITLE
Save multiple resources with one request

### ISSUE THREAD

**Issue by siergiej** [platanus/angular-restmod#117]
How can I make request to save a collection of resources, as described here:
http://jsonapi.org/format/#crud-creating-multiple-resources

I tried doing something like this:
```javascript
Collection.$build({name: 'Smith'});
Collection.$build({name: 'Adams'});
Collection.$build({name: 'Parker'});
Collection.$save();
```

But collection resources don't have a ```$save``` method.

I'd like to avoid saving each resource in a separate request.

**Comment by jpulec** [comment]
Closing as duplicate of #80
