### ISSUE TITLE
Add interceptor support

### ISSUE THREAD

**Issue by iobaixas** [platanus/angular-restmod#12]
In order to meet various implementation specific HTTP requirements some users may have, some kind of request/response interceptor must be provided. I don't think this should be a per request-generating-method thing, but a global/model configuration option.

Any proposals on this subject? @bunzli, @blackjid.

**Comment by eborned** [comment]
I think the main difference between the before-request and an interceptor is that an interceptor can defer the request until another promise is resolved. I don't see a way to do this with restmod and before-request.

A possible usecase for this would be refreshing an oauth access token before it expires. This requires an additional request to the oauth server, before the actual request can be made. I usually implement this with a getToken method that returns a promise. Directly if the token is still valid and deferred if it needs a refresh.
