### ISSUE TITLE
Use custom url for search

### ISSUE THREAD

**Issue by tamaspap** [platanus/angular-restmod#123]
Hy. I'm so happy to find restmod. Used it without problems in some small projects.
However, I would have a question.
I have a `BlogPost` model, and use the `http://domain.com/posts` url to create, update and return blog posts.
But I want to get only blog posts in draft state. The url for that is: `http://domain.com/posts/drafts`.
Can I do a search from by blog post model, using this url for draft blog posts?

I know I can do a `BlogPost.$search({state: "draft"})` which will make a `GET` request to `http://domain.com/posts?state=draft`, but I can't change the url. I must return the drafts from `http://domain.com/posts/drafts`.

Is this possible with restmod?
Thanks!

**Comment by thejayvm** [comment]
@iobaixas Is it possible to do something similar with `$find` - I'm trying to write a "find by something that's not ID" method on a Model.

**Comment by sikko** [comment]
Any idea on how to achieve this on version 1.1.9 ?
I'm getting deprecation warnings when using: '@nest'

**Comment by tamaspap** [comment]
@sikko You can extend your model and make use of ```this.$collection```:

```
function Model(restmod) {
    return restmod
        .model('http://domain.com/someUrl')
        .mix({
            $extend: {
                Model: {
                    customMethod: customMethod
                }
            },
            $config: {
                jsonMeta: "."
            }
        });

    //////////////////////////////

    /**
     * Some custom method.
     *
     * @param params
     * @returns {CollectionApi}
     */
    function customMethod(params) {
        return this.$collection(params, {
            $urlFor: function() {
                return 'http://domain.com/anotherUrl';
            }
        });
    }
}
```
