### ISSUE TITLE
Is $promise.then supposed to receive the results as the first arg?

### ISSUE THREAD

**Issue by scriby** [platanus/angular-restmod#140]
I've been noticing that when I port $resource models over to restmod, that calling `$promise.then` doesn't work quite right.

For example:

```
model.$search({}).$promise.then(function(items) {
  //items is not defined
});
```

However, these ways work:

```
model.$search({}).$asPromise().then(function(items) {});
model.$search({}).$then(function(items){});
```

I was wondering why using `$promise.then` as with $resource models doesn't work in the same way. Is there a subtle difference between it and `$asPromise`?

**Comment by jpulec** [comment]
Closing as solved.
