### ISSUE TITLE
StaticApi does not contain $unwrap

### ISSUE THREAD

**Issue by scriby** [platanus/angular-restmod#141]
I was just noticing in the docs that the StaticApi contains the $unwrap method (http://platanus.github.io/angular-restmod/StaticApi.html#toc29), however, it appears to not actually exist.

For instance:

```
var X = restmod.model(url);

X.$unwrap(data); //$unwrap not defined
```

What I am trying to do is write a custom method which will convert the results to another restmod model type. I am trying to call $unwrap on the other model type directly to do the conversion. Maybe there is a better way?

**Comment by jpulec** [comment]
Closing as solved.
