### ISSUE TITLE
Support both metadata and links at the root element

### ISSUE THREAD

**Issue by adammw** [platanus/angular-restmod#153]
We currently have our APIs structured like so:

``` json
{
  "users": [{
    "url": "http://myapi.org/users/1.json",
    "id": 1,
    "name": "Austin Powers",
    "email": "austinpowers@example.com",
    "role_ids": [1],
  }],
  "roles": [{
    "url": "http://myapi.org/roles/1.json",
    "id": 1,
    "name": "admin"
  }],
  "next_page": "http://myapi.org/users.json?page=2",
  "previous_page": null,
  "count": 10
}
```

I haven't been able to get links to work, and I think it's because the jsonMeta and jsonLinks property are both set to the root element ('.'). Would it be possible for restmod to detect which are links and which are metadata, or manually set which properties are links?

**Comment by maufl** [comment]
@iobaixas What's the state on hasMany and hasOne relations and linked resources? As far as I understand, right now I can have either nested resources (e.g. companies/3/users) or can side load users in company but not both. Is that correct?

**Comment by iabdulin** [comment]
@maufl @iobaixas yeah, I couldn't side load hasMany resources either.
```coffeescript
.factory 'User', ['restmod', (restmod) ->
  return restmod.model('/api/users').mix
    accounts: { hasMany: 'Account', inverseOf: 'user' }
]
.factory 'Account', ['restmod', (restmod) ->
  return restmod.model('/api/accounts').mix
    user: { belongsTo: 'User' }
]
```

```
{
  "user": {...},
  "linked": {
    "accounts": [..., ...]
  }
}
```

user.accounts is empty after fetching user

**Comment by maufl** [comment]
@iabdulin This works for me if I use a `belongsToMany` relationship. But I don't really know if that is the correct way. Furthermore, if I have a cycle in the relations, restmod will go into an infinite loop :(

**Comment by iabdulin** [comment]
@maufl if I simply change
User hasMany Account
to
User belongsToMany Account

it doesn't work :(
