### ISSUE TITLE
Prepend data to collection

### ISSUE THREAD

**Issue by fabiosussetto** [platanus/angular-restmod#163]
Hi, Collection.$fetch allows to append results at the end of the collection. What about the other way round? Have you got an example on how to do that? I was looking at the source code and apparently `$unwrap` calls `$reveal` which in turns call `$add` on the current scope, so I'm not sure what to override if I still want to call `$unwrap` (let's say because I use $action to do a separate request to fetch the next results).  

As an alternative approach, I was thinking about reversing the collection instead, after a normal $fetch.

Thanks again.

**Comment by smajl** [comment]
BTW I ended up using dumb and simple:
```javascript
...
var newItem = collection.$build();
newItem.$moveTo(0);
newItem.$save(); // item is prepended
...
```

**Comment by jpulec** [comment]
Closed as solved.
