### ISSUE TITLE
How to get a collection items position in the collection

### ISSUE THREAD

**Issue by facultymatt** [platanus/angular-restmod#167]
Is there a performant way to get the index of an item in a collection? I'd like to use this index to compare the next and prev items. 

Currently I use this to get the next item but it's not the quickest way: 

```
    $next: function() {
            var thisPoint = this;
            var collection = thisPoint.trip.points;
            var collectionLength = collection.length;
            var index = collection.$indexOf(thisPoint);
            var nextIndex = index < collectionLength - 1 ? index + 1 : index;
            return collection[nextIndex];
     }
```

I noticed that https://github.com/platanus/angular-restmod/blob/master/src/module/api/record-api.js#L384 references $revealAt but this is undefined in my case.

**Comment by aherok** [comment]
So there's no way to do that ? Just some fiddling with sorting after each collection update? IMHO the $revealAt would be good solution.
