### ISSUE TITLE
DirtyModel - detect changes to objects?

### ISSUE THREAD

**Issue by ameswarb** [platanus/angular-restmod#211]
At the moment if you make changes to properties of a model's object, the model won't be flagged as dirty. 

I don't specifically want any granularity (i.e. what property of that object changed), just that the object associated with key x has changed would be good enough.

**Comment by jczerwinski** [comment]
It looks to me like Nested Dirty Model supports this already

**Comment by duhast** [comment]
+1 for tracking array and object field changes

**Comment by jpulec** [comment]
This should be solved with the use of `NestedDirtyModel`.
