### ISSUE TITLE
Get related model from collection object

### ISSUE THREAD

**Issue by jacek-dargiel** [platanus/angular-restmod#220]
Is there a way to access a related model from a collection object?

I have a table displaying the `Bike` model. The Bike model `belongsTo` a `Owner` model. The table has a button to show a filter dialog for the Owner column. Clicking it launches a custom method defined on the collection using `$extend`. From there I want to get the Owner resource, and issue a `$search` for all values to display in the filtering dialog. I don't want to inject the `Owner` service, because I want to make it generic enough to use in other model, and with multiple columns.

Do you have a solution to this problem?

**Comment by jpulec** [comment]
Closing as there is a related issue.
