### ISSUE TITLE
Typo in word $cannonicalUrl

### ISSUE THREAD

**Issue by fabiosussetto** [platanus/angular-restmod#227]
This is about the new $cannonicalUrlFor property:

"cannonical" should really be "canonical": https://www.google.co.uk/search?q=canonical&oq=canonical&aqs=chrome..69i57j69i65l3j69i60j0.1527j0j7&sourceid=chrome&es_sm=91&ie=UTF-8#q=define+canonical

This typo nearly drove me insane as I was trying to search for usage in your library and I couldn't find anything for $canonicalUrl, I was like "I swear I saw it the other day!"  :)

**Comment by iobaixas** [comment]
:+1:  marking this a bug, i'll fix it asap.

The canonical url is the one that betters identifies the resource and is not intended to be used in any specific request, a canonical url can be used, for example, as unique key in object stores. The idea behind the `$canonicalUrlFor` method is to allow the scope to provide a canonical url that is different from the default url, this can be useful for relations extension builders.

**Comment by fabiosussetto** [comment]
Thanks!
