### ISSUE TITLE
How to efficiently save a collection (why no save())?

### ISSUE THREAD

**Issue by ronaldjeremy** [platanus/angular-restmod#228]
Say I have a bikes collection consisting of 30 bikes.  In my application the bikes are listed and the user can drag-n-drop the bikes up or down in the list to sort them to their liking.

Each bike has "sortpos" property to indicate its position in the list.  If a user drags the bike in position 1 down to position 30, it now has sortpos 30 and every bike before it will have their sortpos shifted by -1.

My question is, how can I handle $save()'ing all of this to the server without generating 30 PUT requests that flood the server and slow the app?  It seems like I should be able to do a single "bikes.$save()" PUT to "/bikes" with the body being an array like [{id:1,sortpos:30},{id:2,sortpos:1},{id:3,sortpos:2}...] -- (instead of 30 separate "bike.$save()" PUTs to "/bikes/id" {sortpos:pos})  ?

**Comment by hinok** [comment]
Why not just extend Collection Api?
If you'd like you can always dispatch manually hooks in saveAll()

```javascript
return restmod.model('http://api.com/bikes', {
    $extend: {
      Collection: {
        saveAll: function() {
            // iterate over collection, build data, send put, return promise?
        }
    }
  });
```

**Comment by iobaixas** [comment]
Support for bulk operations is planned for 1.2 as a bundled plugin, you could take part on the discussion in #80.
