### ISSUE TITLE
Nested properties without a relationship

### ISSUE THREAD

**Issue by scriby** [platanus/angular-restmod#229]
Hi,

I've been looking through the docs, but I can't tell if restmod supports something like this:

```
restmod.model().mix({
  property: {
    subProperty: { serialize: 'date' }
  }
});
```

Can I setup nested properties without specifying a relationship?

**Comment by iobaixas** [comment]
Yes you can!

```js
restmod.model().mix({
  'property.subProperty': { serialize: 'date' }
});
```

**Comment by iobaixas** [comment]
I'm reopening to remember to add this to the docs!
