### ISSUE TITLE
$save() method behaviour

### ISSUE THREAD

**Issue by garethhudson07** [platanus/angular-restmod#230]
Hi guys,

I may be getting the wrong end of the stick here but the $save() method is not working as I would expect.

Running the following code:

```javascript
Product.$build({name : 'name', description : 'description'}).$save().$then(function(product) {
        
        product.description = 'updated description';

        product.$save();
});
```

Results in two new resources being created, ie two **post** requests to the server.

I would have expected the second call to $save() to result in a **put** request.

Am I going about this the wrong way?

Thanks in advance :)

**Comment by iobaixas** [comment]
Hi @garethhudson07, what does the server response looks like? maybe is a **primary key** issue. 

Restmod will send a PUT request only if it knows the resource primary key.

**Comment by garethhudson07** [comment]
Hi @iobaixas, Thanks for your reply it led me straight to the problem.

I had neglected to give a resource type in my json response, whoops!

Thanks for your help :)

**Comment by iobaixas** [comment]
:+1:
