### ISSUE TITLE
Best approach for removing circular references

### ISSUE THREAD

**Issue by facultymatt** [platanus/angular-restmod#231]
I have a scenario where I save a model with associations to another scope variable. Theres is a deep watch - `$scope.$watch('thing', true)` - on this variable that MUST remain.

Since my model has associations, there are circular references to its parents, children, etc. This causes a maximum callstack error in angular. 

What is the best approach to "serialize" the model in this instance - what I want is the model properties only and no associations.

**Comment by iobaixas** [comment]
You can serialize the model using `$encode` (is not really serializing, is making it a plain object). That should get rid of every circular reference to associations, scopes, types, etc.

**Comment by jpulec** [comment]
Closing as solved.
