### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by demisx** [platanus/angular-restmod#233]
Are there any best practices on how to implement model validations at the model level? Similar to how models are validated in Rails.

**Comment by iobaixas** [comment]
No, not yet at least, it would make a nice plugin!

In the meantime you could override `$save` and do something like:

```js
restmod.mixin({
  $extend: {
    'Record.$save': function() {
      if(this.$runValidations()) {
         this.$super();
      } else {
         // throw exception?
      }
    }
  }
});
```

**Comment by dirkgroenen** [comment]
For anyone stumbling on this issue: I've created a little validation plugin for my project and shared it on my profile. 

[angular-restmod-validation](https://github.com/dirkgroenen/angular-restmod-validation)

**Comment by karneaud** [comment]
+1 nice @dirkgroenen will try this out
