### ISSUE TITLE
How to remove a record from a collection manually

### ISSUE THREAD

**Issue by tamaspap** [platanus/angular-restmod#238]
In case I have a ```Category``` model and a ```Post``` model, and I implemented a ```move``` method for posts, to move them in another category, I want to remove the ```post``` model from ```category.posts``` collection after it's ```post.category_id``` is updated.

What's the best way to remove the ```post``` model from ```category.posts``` collection?
Should I simply use native ```delete``` operator, or is something special ```restmod``` way to to this?

**Comment by iobaixas** [comment]
You can call `$remove(obj)` on the collection.

**Comment by tamaspap** [comment]
That's great! Would be useful to mention it in docs.
