### ISSUE TITLE
Nested Resource with CamelCase generates request with a '-' 

### ISSUE THREAD

**Issue by glebysg** [platanus/angular-restmod#240]
I have a Sheet model that hast many AirServices. They are defined like this:
```js
alannaApp.factory('AirService', [
  'restmod',
  function (restmod) {
    return restmod.model().mix({
      $config: {
        name: 'air_service',
        plural: 'air_services' 
      }  
    });
  }
]);

alannaApp.factory('Sheet', [
  'restmod',
  function (restmod) {
    return restmod.model('/sheets').mix({
      airServices: { hasMany: 'AirService' },
      clients: { hasMany: 'Client' },
      comments: {hasMany: 'Comment'}
    });
  }
]);
```
When I try to refresh the airService collection by doing this:
```js
var sheet = Sheet.$find(1);
sheet.airServices.$refresh();
```
The generated request is:
**GET /sheets/1/air-services.json**

Instead of:
**GET /sheets/3/air_services.json**

The $config is having no effect in the request's URL.

How can I produce this url for the requests: '/sheets/1/air_services.json' ?

Thank you!

**Comment by iobaixas** [comment]
By default (until 1.2) every relation name is parameterized using '_', to disable this you should override the `encodeUrlName` model method:

```js
alannaApp.config(function(restmodProvider) {
  restmodProvider.rebase('BaseModel');
});

alannaApp.factory('BaseModel', function(restmod) {
  return restmod.mixin({
    'Model.encodeUrlName': function(_name) { return _name; }
  });
});
```

After 1.2 is released this (doing nothing) will be the default behaviour.
