### ISSUE TITLE
Issue when injecting $location into mixin

### ISSUE THREAD

**Issue by facultymatt** [platanus/angular-restmod#243]
I'm writing a mixin that uses the `$location` service.  When I inject this into my mixin, It breaks many other tests. 

Here is the mixin:

```
angular
  .module('SPModels')
  .factory('queryString', ['restmod', '$location', '$rootScope',
    function(restmod, $location, $rootScope) {
      return restmod.mixin(function() {

        var previousParams = {};

        // remove previous params and clear the hash
        function _removePreviousParams() {
          _.each(previousParams, function(paramValue, paramName) {
            previousParams[paramName] = null;
            $location.search(paramName, null);
          });
        }

        // add new params to location and to hash
        function _addParams(newParams) {
          _.each(newParams, function(paramValue, paramName) {
            previousParams[paramName] = paramValue;
            $location.search(paramName, paramValue);
          });
        }

        // bind to before request for this resource
        this.on('before-request', function(request) {
          _removePreviousParams();
          _addParams(request.params);
        });

        // remove all of these when user navigates to new view
        $rootScope.$on('$routeChangeSuccess', _removePreviousParams);
        $rootScope.$on('$stateChangeSuccess', _removePreviousParams);

      });

    }
  ]);
```

The test errors are: 

```
TypeError: 'undefined' is not an object (evaluating '$rootScope.$broadcast('$locationChangeStart', $location.absUrl(), oldUrl).
```

If I don't inject location, things work fine: 

```
angular
  .module('SPModels')
  .factory('queryString', ['restmod', '$rootScope',
    function(restmod, $rootScope) {
      return restmod.mixin(function() {

      });
    }
  ]);
```

The above code throws no errors (but it obviously doesn't work as I need it too!)

**Comment by iobaixas** [comment]
I'm not sure where the problem could be.. maybe it has to do with the way angular mocks `$location`?

About the code, I would be a little worried about registering scope event listeners inside a mixin, since that code will run for every model and you will get N*2 event registrations if you have N models. Maybe is a better idea to use a separate service that gets injected and used inside the mixin? Just a thought...

**Comment by facultymatt** [comment]
Ahh, yes, thats a good point. I hadn't thought about optimization or use cases where more than one model use this mixin, but you are correct that event listeners should not be inside the mixin... I will post an updated example when I handle the optimization. 

Let me see about making a plunkr for this... do you have starting template by chance?

**Comment by iobaixas** [comment]
I found this one on another issue, its a little outdated though... http://plnkr.co/edit/DcsIHDxxlKwhQv8aF0KU?p=preview

**Comment by facultymatt** [comment]
Found the problem on my end... Only tests which used spies were failing. The fix was to use jasmine's `callThrough` method on my spies:

```
spyOn($rootScope, '$broadcast').and.callThrough()
```
