### ISSUE TITLE
Model is not filled when attribute init function is executed

### ISSUE THREAD

**Issue by smashercosmo** [platanus/angular-restmod#246]
Consider the following example:

```javascript
var ItemModel = restmod.model('/rest/items').mix({
  itemId: { 
     init: function(){
        return this.id;
     }
  }
});
```

When items collection is fetched model's itemId property will be undefined.

**Comment by IjinPL** [comment]
+1

**Comment by iobaixas** [comment]
That's the expected behaviour, `init` is called once when the object is constructed, not every time server data is decoded into the object, to calculate an attribute value using information retrieved from server you could use the `after-feed` hook (or a computed property).

**Comment by smashercosmo** [comment]
Ok, I got it. Actually I need something like propery mapping, but existing solution doesn't fit my needs, because it removes original property. So when I'm doing something like 

```javascript
var ItemModel = restmod.model('/rest/items').mix({
  itemId: { 
     map: 'id'
  }
});
```
I get model with only itemId presented. And I need both id and itemId. So, the hook solution is the only one, right?

**Comment by smashercosmo** [comment]
I figured out I can write

```javascript
var ItemModel = restmod.model('/rest/items').mix({
  itemId: { 
     map: 'id'
  },
  id: {
     map: 'id'
  }
});
``` 
And it works))) But pretty ugly though)

**Comment by jpulec** [comment]
Closed as solved.
