### ISSUE TITLE
Add package to npm

### ISSUE THREAD

**Issue by zenwalker** [platanus/angular-restmod#247]
Please, add this package to npm. It's not only for server packages.
http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging

**Comment by iobaixas** [comment]
@zenwalker, any suggestions for the `package.json` manifest?

**Comment by zenwalker** [comment]
* Add main [entry point](https://docs.npmjs.com/files/package.json#main) to program
* Add a dependency on [angular-inflector](https://github.com/iobaixas/angular-inflector) (if entry point is not bundled version)
