### ISSUE TITLE
Best way to handle extra Rails Custom API 

### ISSUE THREAD

**Issue by restogeek** [platanus/angular-restmod#248]
Let's say that my Rails Controller is defined as follows:
```ruby
def CategoriesController < ApplicationController

  def index ... end
  def show ... end
  def create ... end
  def update ... end
  def destroy ... end

  def roots
    @categories = Category.roots
    render index
  end

end
```
What is the best way to add 'roots' to my restmod implementation on angular?

Thank you!

**Comment by restogeek** [comment]
Currently, with ngResource, I define it as:

'roots': { method: 'GET', url: '/api/categories/roots', isArray: true }

**Comment by restogeek** [comment]
Another example is if I have to map to my Products index with the following server REST API url:
Index of all products
```
/api/products
```
Index of the products belonging to a given Category
```
/api/categories/:categoryId/products
```

Thanks all for your help!

**Comment by aeldaly** [comment]
I have the same question

**Comment by iobaixas** [comment]
I'll start with the second question,

You could use the following structure:

```js
module
.factory('Product', function(restmod) {
  return restmod.model('api/products');
})
.factory('Category', function(restmod) {
  return restmod.model('api/categories').mix({
    products: { hasMany: 'Product' } 
  });
});
```

Then you can do `Category.$new(1).products.$fetch()` to retrieve the products belonging to the category with id=1;

As for your first question, currently there is no easy way of providing a collection an explicit url (like `/api/categories/roots`), I'll add this to the 1.2 milestone.

**Comment by jpulec** [comment]
Closing as tracked in another issue.
