### ISSUE TITLE
No error callback on second $then

### ISSUE THREAD

**Issue by johannesspohr** [platanus/angular-restmod#250]
Hi everybody, 
I'm trying to chain multiple $then, but, while, the first one correctly calls success or error, all following only fire the success callback. Is there anything i can do about it?
Code looks like:
```
 return this.$find(id).$then(function (res) {
                        console.log('success');
                    }, function (error) {
                        console.log('error');
                    }).$then(function () {
                        console.log('success1');
                    }, function () {
                        console.log('error1');
                    });
```
In case of an error, it prints error and success1.
Thanks a lot!

**Comment by cthrax** [comment]
This is actually expected promise behavior, propagating success. http://know.cujojs.com/tutorials/async/mastering-async-error-handling-with-promises Basically you need to throw an error to get the next promise to error.

**Comment by johannesspohr** [comment]
Alright, i wasn't aware of that. Thanks!
