### ISSUE TITLE
Converting empty value to null for every model attribute

### ISSUE THREAD

**Issue by jamhall** [platanus/angular-restmod#252]
Hello,

Is there a way that before sending an object to be created/updated, I can check if a value being sent is empty ("") is empty and if it is, it is converted to null?

My backend does not accept empty strings.

Thanks!

**Comment by jczerwinski** [comment]
You could try a hook. From [the docs](https://github.com/platanus/angular-restmod/blob/master/docs/guides/hooks.md):

```javascript
var Bike = $restmod.model('/bikes', {
  $hooks: {
    'before-save': function() {
      if (this.name === '') this.name = null;
    }
  }
});
```

You might want to change it back after the save is complete, too, though I'm not sure if that's necessary. Haven't used it myself yet.

**Comment by jamhall** [comment]
Hi.

Thank you for your reply.

I did it the following way:

```
 restmod.model(null).mix({
     website: {
         encode: function(_value) {
             return (_value === '') ? null : _value;
         }
     }
 });
```

I defined an encode method for every model attribute where I want an empty string to nullified.

It's a shame I can't create a base attribute encoder for this that applies to all models without having define an encode method on each model attribute.

**Comment by iobaixas** [comment]
Yes you can!, you can use angular filter names instead of functions, so you can create a custom filter and apply it to the attributes you need to convert. Check out https://github.com/platanus/angular-restmod#encode.

**Comment by iobaixas** [comment]
But you are right, is not a 'base encoder' so it can't mix with other encoders... There is a way in restmod of chaining encoders/decoders but is not supported by the definition object.

**Comment by jpulec** [comment]
Closing as solved.
