### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by aeldaly** [platanus/angular-restmod#253]
```
angular.module('wpitcApp:components:article')
  .factory('Wordpress', function Wordpress(restmod) {
    var blogUrl = 'https://public-api.wordpress.com/rest/v1/sites/wp-api.weddingplannersinthecity.com/';

    var wordPress = restmod.model('/posts')
      .mix('DefaultPacker', {
        $config: {
          urlPrefix: blogUrl
        },
        $extend: {
          Model: {},
          Record: {}
        }
      });

    return wordPress;
  });
```

In a controller, I have:

```
Wordpress.$collection().fetch();
```

Which throws:
```
TypeError: Converting circular structure to JSON
```

Any idea what's happening here?

**Comment by iobaixas** [comment]
That's estrange, `JSON.stringify` should only be called when using `$save` (`$encode`), are you sure that the error is being thrown during the `$fetch` call?

**Comment by aeldaly** [comment]
Yes, this happens when I assign a variable to the call, then in the view, for troubleshooting purposes try to display it. e.g., in controller:

```
wp = Wordpress.$collection().fetch();
```

and in view:

```
{{ wp }}
```

**Comment by iobaixas** [comment]
I think the problem is related to the way angular serializes an object when you call `{{ wp }}`, since wp has circular references inside of it, when angular tries to serialize it using JSON.stringify it breaks. Try calling  `{{ wp.$encode() }}` instead.
