### ISSUE TITLE
Update dependencies property in bower.json

### ISSUE THREAD

**Issue by Pleasurazy** [platanus/angular-restmod#259]
Hello, I am using Bower and [wiredep](https://github.com/taptapship/wiredep)

angular-restmod's bower.json seem only:

```json
  "dependencies": {
    "angular-inflector": "~0.2.0"
  }
```

It make wiredep inject scripts with wrong order.

![image](https://cloud.githubusercontent.com/assets/1500206/6244157/644f702c-b78a-11e4-9444-ac9673034981.png)

If i overrde restmod dependencies in [wiredep#configuration](https://github.com/taptapship/wiredep#configuration)

![image](https://cloud.githubusercontent.com/assets/1500206/6244228/5557700a-b78b-11e4-813b-850192a3ae5a.png)

It work.

![image](https://cloud.githubusercontent.com/assets/1500206/6244173/a2c00a6a-b78a-11e4-9162-3eedce47e1b7.png)

**Comment by iobaixas** [comment]
You are right, I'll add this as a bug to be fixed before 1.2. Thanks!
