### ISSUE TITLE
Confused about addItem to $Collection

### ISSUE THREAD

**Issue by episodeyang** [platanus/angular-restmod#261]
Hi @iobaixas 

This is a great library! it replaced tons of my custom model code.

I have been struggling with the relationships in restmod. Here is my basic use:

```
GET /api/notes/ gives:
    note : {
          comments: {
                 id: ""
          }
    }
```

any update to a comment should go to 
```
POST /api/comments/:commentId
```

However, the problem I am having is with `$addCommentToNote`. Since there are a lot of validation, I want this request to be of the form
```
PUT /api/notes/:noteId/comments/
```

When the server responses, I want the server to <b>only</b> serve the new comment created, instead of sending back the entire collection of updated comments. But then I had problem `unpacking` the `_response` data. 

What is the best practice for this?

If what people usually do is to send back the list of comment ids, it would work for me too. I would like to know what you guys do with your API.

**Comment by episodeyang** [comment]
I played around a bit, does both `belongsToMany` and `hasMany` support populated subdocuments? and the only difference between these two is how the CRUD request url's are handled? 

What about if I want to use the following CRUD url:

```javascript
Create:  PUT /api/notes/:noteId/comments/
Read:    GET /api/notes/:noteId
Update: POST /api/comments/:commentId
Delete: DELET /api/comments/:commentId
```

**Comment by episodeyang** [comment]
Right now if I use `hasMany`, the `$destroy` method actually sends `DELETE /api/comments/:commentId`, but I need `DELETE /api/notes/:noteId/comments/:commentId` instead.

**Comment by npearson72** [comment]
You may want to looking at extending your model. Just off the top of my head, it would be something like:

````
return restmod.model('your/url').mix({
  $extend: {
    Record: {
        $destroy: function() {
           this.$super('modify/your/path/here')
      }
    }
  }
})
````

**Comment by episodeyang** [comment]
Thanks @npearson72 !!

This is a very nice and powerful library. But I have found myself from time to time run into problems due to lack of documentation, and sometimes looking through the code could also be unhelpful. 

This is why quick replies and pointers are actually very helpful. It gives me something to work with.

Thanks!

**Comment by npearson72** [comment]
I'm a consumer just like you.
