### ISSUE TITLE
Simple Question: How to remove document from `hasMany` collection

### ISSUE THREAD

**Issue by episodeyang** [platanus/angular-restmod#263]
have been trying to figure this out for 45 minutes now! 

say we have two models, where the bike has many parts. 

If I want to generate the following request: 

```javascript 
DELETE /api/bikes/:bikeId/parts/:partId
```

What method shall I use, and how do I use it? Right now if I call `$destroy` on the part, it just gives
```javascript 
DELETE /api/parts/:partId
```

Thanks!

**Comment by episodeyang** [comment]
I read the README again (this has to be the 20th time now), and just realized that if `parts` model has no url defined, all CRUD goes through `bike`. 

Now stuff is working, however I still like to have a few other operations go through the `/api/parts/:partId` endpoint instead of having everything go through `bike`. 

Is this doable? 

Thanks!

**Comment by eborned** [comment]
Any luck with this problem? I'm having the same issue:

Playlist (/playlist/{id})
Playlist hasMany Tracks (/playlist/{id}/tracks)

But tracks are global entities. I would like to add or remove tracks from a playlist collection, but not the track itself.

When I do playlist.tracks.$fetch() I get track objects. But when I destroy them, it destroys the track itself, not the relation. Am I missing something here?

**Comment by agustinf** [comment]
From a REST point of view, you shouldn't "destroy a Track" to remove it from a Playlist, it is the **relation** between a Track and a Playlist what you "create" or "destroy". This **relation** is a resource in itself, different from Track, and should have its own Model.

Playlist hasMany PlaylistTracks
