### ISSUE TITLE
Default paremeterization of urls will be disabled in 1.2?

### ISSUE THREAD

**Issue by npearson72** [platanus/angular-restmod#266]
What does this message mean, and how can I resolve it?

Default paremeterization of urls will be disabled in 1.2, override Model.encodeUrlName with inflector.parameterize in your base model to keep the same behaviour.

**Comment by restogeek** [comment]
+1

**Comment by restogeek** [comment]
Anybody understands this issue? It is a big problem on performance on my side.

**Comment by aantipov** [comment]
+1

**Comment by jgoux** [comment]
Any news on this ?

**Comment by smajl** [comment]
This: http://platanus.github.io/angular-restmod/tutorial-integration.html#q11

Simply extend your model with own `encodeUrlName()` function. *Warning gone*.

**Comment by jczerwinski** [comment]
I'm having trouble implementing the suggested default behavior here:

```javascript
module.config(['restmodProvider', 'inflector', function (restmodProvider, inflector) {
	restmodProvider.rebase({
		$extend: {
			Model: {
				encodeUrlName: inflector.parameterize
			}
		}
	});
});
```
Gives this error:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module myModule due to:
Error: [$injector:unpr] Unknown provider: inflector
```
Obviously I would need to depend on `inflectorProvider` here, not `inflector`, but `inflectorProvider` doesn't expose `parameterize()`, which is what I need.

Sure, I could use a mixin, or set `encodeUrlName()` on each model individually, so its not a big deal. But when the recommended solution in the error message is to use `inflector.parameterize`, and the most direct way to emulate the current default behaviour would be using `rebase()`, it feels a bit hacky.

Not sure what the solution to this is. Enable limited rebasing on `restmod` itself? Refactoring `inflector`? Maintaining the current default behaviour and backtracking on the planned change? Or just asking users to use mixins/model-level overrides?

**Comment by smashercosmo** [comment]
@jczerwinski you just need to implement your restmod mixin as a factory, where you can inject inflector. And then in config block use your factory name as an argument for rebase method.

**Comment by jczerwinski** [comment]
Just realized that and deleted my comment :)

**Comment by jpulec** [comment]
Closed as solved.
