### ISSUE TITLE
When 1.2 release ?

### ISSUE THREAD

**Issue by sandwich99** [platanus/angular-restmod#274]
Angular-restmod 1.2 has much interesting features , I 'm really looking forward

**Comment by smashercosmo** [comment]
Yeah, guys, we definitely need more frequent releases)) Bescause it's more than a month since last release.

**Comment by iobaixas** [comment]
I'm having trouble putting enough time on this project, I need to enrol more people to help with answering questions and coding (also I was on vacations).

It takes a lot of work going through the pending issues and answering pending questions, I hope I get some free time to work on the new features this week.

**Comment by iobaixas** [comment]
Updated release date

**Comment by smashercosmo** [comment]
I think that date should be updated again ))
