### ISSUE TITLE
Update package.json to support JSPM package manager

### ISSUE THREAD

**Issue by aptogo** [platanus/angular-restmod#275]
Related to #125 

Please change the main entry point in `package.json` to `dist/angular-restmod-bundle.js`. This property is used by the JSPM package manager to determine how to expose the package and the inflector is missing unless the bundled dist file is used. 

Also, please remove the dependency on angular-inflector - this dependency is satisfied in angular-restmod-bundle.

**Comment by iobaixas** [comment]
Main entry point was changed, i'm not sure about removing the inflector dependency, it could lead to code breaking for people using the non-bundle version.
