### ISSUE TITLE
Set serializer for property of object in array

### ISSUE THREAD

**Issue by chellstrom** [platanus/angular-restmod#278]
Suppose I have an endpoint `/books/:id` that returns data like:

```javascript
{
  id: 123,
  name: '1984'
  editions: [
  {
    publisher: 'Penguin',
    date: '1950-01-01'
  },
  {
    publisher: 'Random House',
    date: '1960-01-01'
  }]
}
```

And the `editions` property doesn't correspond to it's own endpoint.  Is there a way to set the serializer for the `date` property for every object inside `editions`?  Something like:

```javascript
var Book = restmod.model('/books').mix({
    'editions.date': {serialize:'date'}
});
```

It seems like in order to set a special attribute on a field, that field must be at the top level of the object returned by the endpoint.

**Comment by scriby** [comment]
+1

**Comment by iobaixas** [comment]
Since edition is an array, you can refer to it in the definition object by using `[]`.

```js
var Book = restmod.model('/books').mix({
    'editions[].date': {serialize:'date'}
});
```

**Comment by chellstrom** [comment]
That works as expected - thanks!
