### ISSUE TITLE
how to test my model

### ISSUE THREAD

**Issue by boiawang** [platanus/angular-restmod#279]
if I have a model

```
.factory('MyModel', function(restmod){
  return restmod.model('/user')
})
```

How can I write unit test for MyModel?

**Comment by smashercosmo** [comment]
It depends on what do you want to test

**Comment by fabiosussetto** [comment]
This is how I'm doing it:

timeline = TimelineModel.$new(1);
timeline.$unwrap({name: "Test", description: "Bar..."});

then you have a timeline model you can unit test.
