### ISSUE TITLE
Handle dynamically generated property names in models

### ISSUE THREAD

**Issue by blaiz** [platanus/angular-restmod#282]
I've got an API that returns data in a format similar to this:

```
{
  "someProperty": {
    "_1_1": { 
      some child object here
    },
    "_2_1": {
      some other child object here
    }
  }
}
```

As you can see, this is a map of objects where the keys are IDs, which means they are dynamically generated. The child objects are represented by a restmod model, but I don't see how to setup the relationship between the 2 models since the property names are dynamic.

Right now, I use the `after-feed` hook to manually convert the raw data to the proper model, by looping over the results. Is there a simpler way to do that with restmod?

**Comment by agustinf** [comment]
This is somehow out of scope right now, we are not planning on extending the current relations behaviour.

Take a look at [src/module/extended/builder-relations](https://github.com/platanus/angular-restmod/blob/master/src/module/extended/builder-relations.js) to see if you can modify the code for your convenience.
