### ISSUE TITLE
How to access URL params from inside hooks

### ISSUE THREAD

**Issue by blaiz** [platanus/angular-restmod#285]
Let's say I have a model named `fruits` that has a one to many relation with a parent named `aisles` which itself has a one to many relationship with a parent named `store`.

To retrieve all fruits, I can therefore do something like `StoreModel.$new(123).aisles.$new(321).fruits.$fetch();`

Now, in a hook that contains response data (such as `after-fetch`), I want to access the IDs for the store and the aisle (123 and 321). How can I do that?

I'm looking at the `http-response` object being passed to the hook function, and sometimes it contains those IDs (in `config.params`) but sometime it doesn't.

Is this the recommended way to do this? How to make sure that I can always access those IDs in that hook response object?

Right now one way I can retrieve the store ID from the hook on the fruits model is by using `this.$scope.$scope.$scope.$scope.$scope.$scope.$scope.id`.

**Comment by agustinf** [comment]
Before going into detail: you are performing $fetch on a collection, right? shouldn't you look at the `after-fetch-many` hook ?

**Comment by blaiz** [comment]
Yes, you're right. But I think the issue still stands there.

My actual endpoint is a little more complex (see https://github.com/platanus/angular-restmod/issues/282). I used a hook to properly wrap the result with restmod so that they are real restmod object and I can then call `$save` on them. To wrap them, I have to do something like `StoreModel.$new(123).aisles.$new(321).fruits.$decode(arrayOfFruits)` and I'm looking for the best way to get the IDs.

**Comment by agustinf** [comment]
I'm not an expert here, but perhaps you can use $decorate to store the request params on the http_response object of the after-fetch-many hook. [Take a look at this example](https://github.com/platanus/angular-restmod/blob/master/docs/guides/hooks.md#5-hooks-that-apply-only-to-a-certain-execution-context-using-decorate-used-mainly-to-modify-a-method-behaviour) for inspiration

**Comment by iobaixas** [comment]
Hi @blaiz, you could use the following mixin (**untested**) for your models:

```js
module('module').factory('AnscestorMixin', function(restmod) {
  return restmod.mixin({
    $config {
        hasMany: {
          hooks: {
            'after-feed-many': function() {
              angular.forEach(this, function(item) {
                item.$ancestors = angular.copy(this.$owner.$ancestors || {});
                item.$ancestors[this.$owner.$type.getProperty('name')] = this.$owner;
              });
            }
         }
      }
  });
 });
```

Then you can do

```js
var fruits = StoreModel.$new(123).aisles.$new(321).fruits.$fetch();
// and the following will be available:
fruits[0].$ancestors.store.id
fruits[0].$ancestors.aisle.id
```

Make sure you use `$` in `$ancestors` to avoid sending them to the server when throwing fruit at it.

Cheers!

**Comment by blaiz** [comment]
I gave it a quick try but it didn't work. For some reason my restmod model objects don't have the `$owner` property.
