### ISSUE TITLE
TypeError: Cannot read property '$fetch' of undefined

### ISSUE THREAD

**Issue by bhulkuas** [platanus/angular-restmod#286]
i have two models as shown...

app.factory('Event', function(restmod) {
    return restmod.model('v1/events').mix(
        {
          user: {belongsTo: 'User', key: 'user_id'}
        }
      );
  });

app.factory('User', function(restmod) {
    return restmod.model('v1/users');
  });

i have a controller that lists the events present in the database 

app.controller('EventsController', function($scope,Event,User) {
    
    $scope.eventsList = [];

    var events = Event.$search().
    for (event in events) {
      e.user.$fetch();
    }
      $scope.eventsList = events;
  });

i am getting an error - TypeError: Cannot read property '$fetch' of undefined
for the line 'e.user.$fetch();'

i cannot figure out what is wrong in the code. can anybody help please.

**Comment by agustinf** [comment]
I don't know if you pasted pseudo code or what, but I can't see how you expect `for (event in events)` to have `e` defined. 
Also, sorry to tell you this but please don't use these Github Issues for debugging your code...I'm closing this as there is no real Restmod issue here.

**Comment by bhulkuas** [comment]
It isn't  pseudo code. I changed it to 

var events = Event.search();
for (event in events) {
    event.user.fetch();
}

I still get the same error. I have checked the network tab of developers tool in chrome and found that the server responds with data but still i get this error. 

Sorry for opening an issue for a such a trivial problem but i am new to angularjs and restmod and i think with very little documentation available you should help.

**Comment by blackjid** [comment]
can you show the response you get from the server??

**Comment by bhulkuas** [comment]
0: {id: "1", name: "birthday", user_id: "1", date: "2015-04-16", description: "birthday", active: "0"}
1: {id: "2", name: "anniversary", user_id: "2", date: "2015-04-08", description: "anniversary", active: "1"}
