### ISSUE TITLE
Custom method for POST request

### ISSUE THREAD

**Issue by klautcomputing** [platanus/angular-restmod#294]
Hi,

let's say I have an API where you can request Questions and once you answered them you might want to get new questions, therefore the API has post: /api/questions/next and next gets a couple of parameters, e.g. the question category. Therefore, I would like to write a custom post to /api/questions/next. I took a look at https://github.com/platanus/angular-restmod/blob/master/docs/guides/hooks.md and "5. Hooks that apply only to a certain execution context using $decorate, used mainly to modify a method behaviour" seemed to be exactly what I would like to do:
```javascript
  return restmod.model('/api/questions', {
    $next: function(_params) {
      return this.$decorate({
        'before-request': function(_req) {
          _req.method = 'POST';
          _req.data = _params;
        }
      }, function() {
        return this.$fetch();
      });
    }
  });
```
But this doesn't work and also tells me that: "Passing mixins and difinitions in the model method will be deprecated in restmod 1.2, use restmod.model().mix() instead." So I tried:
```javascript
  return restmod.model('/api/questions').mix({
    $extend: {
      Model: {
        $next: function(_params) {
          return this.$decorate({
            'before-request': function(_req) {
              _req.method = 'POST';
              _req.data = _params;
            }
          }, function() {
            return this.$fetch();
          });
        }
      }
    }
  });
```
But this gives me: TypeError: this.$decorate is not a function
So my question is: how do I create a custom post request in restmod? So that I can just execute this:
```javascript
Questions.$next({category: "awesome"});
```
to retrieve the next questions to be answered. Is there maybe an easier way (which I missed) to do exactly this? Coming from other libraries where it is as easy as doing this:
```javascript
    next: {
      method: 'POST',
      isArray: true,
      url: '/api/questions/next.json'
    }
```
 the restmod way seems to be really complicated (which would be ok), but it doesn't seem to work.

cheers, leex

**Comment by danieljaniga** [comment]
+ 1

**Comment by mbajur** [comment]
+1

**Comment by mtyeh411** [comment]
+1

**Comment by sikko** [comment]
:+1:

**Comment by iobaixas** [comment]
You were almost right! @klautcomputing, the model *type* does not provide a `$decorate`, but as your method needs to return a `$collection`, you could decorate a new `$collection`, like this:

```javascript
 return restmod.model('/api/questions').mix({
    $extend: {
      Model: {
        $next: function(_params) {
          return this.$collection().$decorate({
            'before-request': function(_req) {
              _req.method = 'POST';
              _req.data = _params;
            }
          }, function() {
            return this.$fetch();
          });
        }
      }
    }
  });
```
This is also related to #70
