### ISSUE TITLE
hasMany and null

### ISSUE THREAD

**Issue by kgaree** [platanus/angular-restmod#296]
I have a Course and Concept model
```
service.factory('Course', function(restmod) {
  return restmod.model('/api/courses').mix({
    concepts: { hasMany: 'Concept' }
  });
});
```
If no Concepts are assigned to a Course, mongoose will return null(see below). restmod is expecting an array. In this example restmod is expecting an empty array. Since mongoose populates it as null would it be acceptable for restmod to allow for null?
```
{"name":"Math","concepts":null}
```

**Comment by iobaixas** [comment]
You could add null data support by overwriting the `$decode` method:

```javacript
$extend: {
  'Collection.$decode': function(_raw) {
    this.$super(_raw || []);
  }
} 
```

We are adding support for null in hasMany relations in the next release (1.1.10)
