### ISSUE TITLE
Problem with Rails strong params

### ISSUE THREAD

**Issue by softmonkeyjapan** [platanus/angular-restmod#297]
As this library sounds promising, I wanted to give it a try. However, I'm facing an issue when posting data to my Rails server. Using Rails 4 and strong params, my Rails Api is expecting the resource to be namespaced on post/put/patch : 

```json
{
  "user" : {
    "name": "New user",
    ...
  }
}
```

When issuing a post : 

```javascript
user = User.$build({ name: 'New user' })
user.password = '123456789';
user.$save()
```

`angular-restmod` is actually sending it that way : 

```
Parameters: {"email"=>"test@test.nc", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "role"=>"partner", "name"=>"Test", "subdomain"=>"dev-api", "user"=>{"name"=>"Test", "role"=>"partner", "email"=>"test@test.nc"}}
```

which trigger validations errors as the required params (e,g password) are not under the `user` namespace. I've tried to use $config to set a name for the resource but it does not change the way this behave : 

```javascript
module.factory('User', function(restmod) {
    return restmod.model('/users').mix({
        $config: { name: 'user' }
    });
});
```

Any idea?

**Comment by jczerwinski** [comment]
https://github.com/platanus/angular-restmod/blob/master/docs/guides/integration.md#q2

**Comment by mbajur** [comment]
That problem is not about getting a request @jczerwinski but about sending it. 

I'm having exact the same issue right now and i'm really curious if there is any to-go solution for this.

**Comment by mbajur** [comment]
I have temporary managed to fix that by using a following snippet:

```
restmod.model 'items', {
    $hooks:
      'before-request': (_req) ->
        return _req if _req.method not in ['PUT', 'POST']

        originalData = _req.data
        _req.data = { item: originalData }
  }
```

**Comment by iobaixas** [comment]
@softmonkeyjapan we are using the same stack and relied on rails automatic object wrapping capabilities to take care of this.

I agree that packing-unpacking behavior is not consistent, i'm adding an issue to add json root support on requests too.

**Comment by Nowaker** [comment]
@iobaixas What are exactly these "automatic object wrapping capabilities" in Rails? Or, how to make this `params.require(:person).permit(:name, :age)` work with `{"name": "a", "age": 2}` coming in? Appreciating your help. Thanks.
