### ISSUE TITLE
Compatibility with angular 1.4

### ISSUE THREAD

**Issue by svenstaro** [platanus/angular-restmod#299]
We ran into compatibility issues using angular-restmod with angularjs 1.4.

We got a model with hasMany and resolving that model works fine. However, calling $resolve() on the sub-collection referenced by hasMany seems to give us empty results.

**Comment by arthurspa** [comment]
I had the same problem. I did a workaround.

Please, see [#328](https://github.com/platanus/angular-restmod/issues/328)

I hope it helped!

**Comment by iobaixas** [comment]
This case is missing some key data to give a proper response and is too old, i'm closing it for now but feel free to open it again if the problem continues.
