### ISSUE TITLE
Restmod Factory Only Called Once

### ISSUE THREAD

**Issue by bontorhumala** [platanus/angular-restmod#304]
Hello, great project. We designed our REST API to have auth token that must be submitted along every GET request. We use restmod mixin:

    .factory('Node', function(restmod, Authenticate){
      return restmod.model('../emma/api/web/node').mix( { $hooks: Authenticate.controllerToken() } );
    })

Where we got the controller token via a factory:

    .factory('Authenticate', function(restmod, $auth, $sessionStorage){
    var header = {};
    var hook = {};
    var storage = $sessionStorage;

    header.userToken = function() {
      var hook = {};
      var head = {};
      
      if ($auth.isAuthenticated()) { 
        head = {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
          'emma-user-token': storage.usertoken
        };
      } else {
        head = {
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        };
      }

      hook = {'before-request': function(_req) {
        _req.headers = _req.headers || {};
        _req.headers = head;
      }};
      console.log("header: ", head);
      return hook;
    }

and call the restmod model factory from our stateprovide (using ui-router):

      .state('home', {
        url: "/home",
        cache: false, //required
        templateUrl: "views/home.html",
        controller: 'HomeCtrl',
        resolve: {
          devices: function($auth, $rootScope, NodesControl) {
            if ($auth.isAuthenticated) {
              $rootScope.isLogged = true;
            }
            return NodesControl.$search().$asPromise();
          }
        }
      }) 

But this way, factory only called once, so that when user pick different node (he/she will get new token based on that node), the request will be submitted using the first token, so that user get wrong data. Is this possible in restmod? To use different token for different request?

**Comment by jczerwinski** [comment]
It is difficult to tell exactly what you are asking for from this example.

It sounds like the token you use is dependent on the node(s) you are attempting to GET. In that case, assuming you already have some set of tokens correspending to these nodes, you'd want to do something like this:

```javascript
hook = {'before-request': function(_req) {
    _req.headers['emma-user-token'] = getTokenByNode(this); // `this` refers to your restmod Node record/collection
}};

function getTokenByNode(node) {
    // Do something to get your node-dependent token here. eg:
    return storage.tokens[node.id];
}
````
Ultimately, this does not appear to have anything directly to do with restmod, and has more to do with the logic you're using to select your auth token.

**Comment by iobaixas** [comment]
Thanks @jczerwinski!
