### ISSUE TITLE
How to test resmod with promises ?

### ISSUE THREAD

**Issue by 6ewis** [platanus/angular-restmod#306]
```
// code
visits = RestModVisit.$collection({
  ...
});

visits.$refresh();

visits.$then(function(data) {
  scope.data = data
  scope.formattedData = formattedData
  console.log("abracdabra");
});
```
whenever I run my test suite the promise never resolves. $rootScope.$apply() does not propagate promise resolution to $then so "abracdabra" is never shown.
Is my only option to mock it?

**Comment by smashercosmo** [comment]
you need to use .$asPromise() method. $then doesn't return promise.

**Comment by 6ewis** [comment]
@smashercosmo same issue with visits.$fetch().$asPromise().then(function() {....})
(note: I use rootScope.$apply() in a afteEach() block in my test)

**Comment by smashercosmo** [comment]
mmm... I asume that your problem is that you don't invoke $httpBackend.flush() after you make a server request

**Comment by 6ewis** [comment]
thanks! It solved it , I totally forgot to flush =)
