### ISSUE TITLE
Set url per resource method? 

### ISSUE THREAD

**Issue by facultymatt** [platanus/angular-restmod#308]
Is it possible to set a baseUrl / url per method? 

For example, 

GET http://api1.com/users/123
GET http://anotherapi.com/users/123/wheels

?

**Comment by jczerwinski** [comment]
Set your API route per model:

```javascript
restmod.model('/wheels', {
  $config: {
    urlPrefix: 'http://anotherapi.com'
  }
})
```

If you need something more complex, use [hooks](https://github.com/platanus/angular-restmod/blob/master/docs/guides/hooks.md).
