### ISSUE TITLE
Problem with decode:

### ISSUE THREAD

**Issue by flatr0ze** [platanus/angular-restmod#314]
Got two timestamp keys in my /artists/<ID> end-point, namely DOB and DOD.
Angular-restmod is unable to perform decode: on them though DOD: {decode <function/reference>}, yet that same decode: part works fine if I just apply it to any other key (Name, LastModified, etc). It may have sometihng to do with the API style or the way the restmod parses the property names.
It's a very strange issue indeed, but nevertheless, the decode is ignoring those properties.
Thanks.

**Comment by flatr0ze** [comment]
the keys which consist only of capital letters are not being passed during the PUT method

**Comment by flatr0ze** [comment]
correction: they are not being initialized

**Comment by ldlsegovia** [comment]
@flatr0ze can you show me the code where you are defining `decode`? thanks

**Comment by flatr0ze** [comment]
Hello.

I'm not allowed to do so based on my contract, sorry about that.

The bottom line is that the decoder didn't work for key names under 4 characters.

I ended up writing two additional rules for that model to rename DOB to DateOfBirth and then back to DOB upon saving, that solved the situation.

Has something to do with camelCase transcription.

Please let me know if you'd like me to write a unit test for this case.
Should be easy to reproduce with the description given in this issue though.

Cheers.

**Comment by iobaixas** [comment]
As you said, this has to do with the inflector not being able to properly encode `DOB`, could you try using a explicit mapping? like this:

```javascript
DOD: { decode: yourDecodeFun, map: 'DOD' }
```
