### ISSUE TITLE
How to change the response to an error

### ISSUE THREAD

**Issue by hrajchert** [platanus/angular-restmod#315]
Hi, I my REST server is in a different domain than the application, so because of CORS, whenever the server needs to send an error it responds with status code 200, but in the data I have a special property called `_http_status` with the real status code.

So I'm trying this in the global configuration, but I cannot modify the response from a success to an error.

```js
this.on('after-request', function(_rsp) {
	if (_rsp.data.hasOwnProperty('_http_status')) {
		// This modifies the answer, but doesn't change from success to error
		_rsp.status = _rsp.data._http_status;
		_rsp.statusText = _rsp.data.error_code;
	}
	return _rsp;
});
```

The data changes, but is still treated as valid

**Comment by ldlsegovia** [comment]
@hrajchert It's not possible to change the http status after request is done. Maybe, you can build [your own custom method](https://github.com/platanus/angular-restmod#custom-methods) to achieve this goal.
