### ISSUE TITLE
Performance of extendOverride

### ISSUE THREAD

**Issue by scriby** [platanus/angular-restmod#318]
Our unit tests at work were starting to get pretty slow, so I kicked on the profiler. I found about half (!) of the total time spent when running tests was coming from one method in restmod: Utils.extendOverriden.

Here's a profile of running 20% of our tests: http://screencast.com/t/Bwhk3Iili5

I'm not sure if this is something you were already aware of or not, or if possibly there's something strange about our environment which is a contributing factor.

Thanks,

Chris

**Comment by scriby** [comment]
I think this has to do with angular tearing things down between tests, so it's forced to rebuild the models after each test file. We have quite a few models, so the time adds up.

**Comment by iobaixas** [comment]
I'm closing this issue, we are planning on adding model mocks and helpers in the "future", maybe that will help on improving performance.
