### ISSUE TITLE
Fetching a single object without ID

### ISSUE THREAD

**Issue by philippeluickx** [platanus/angular-restmod#319]
My situation is that I have an authenticated user (by passing a token in the headers) that I would like to fetch the user details for.
In my backend, I go to the same url for any user. No need to pass an ID, as the token will define which user is who.
However, I can not pass an empty find()...

```javascript
// Does not work
var test = restmod.model('auth/user/').$find();
```

Is there any elegant way to deal with this? I am pretty much open for any good design suggestions as well. Thing is that I only have the users token at this point...

Thanks!

**Comment by philippeluickx** [comment]
As a hack, I can do
```javascript
var test = restmod.model('auth/').$find('user');
```

But that's a hack...

**Comment by NineInchLines** [comment]
You can do it by overriding $buildUrl in a model, like so:

    restmod.model('/auth/user').mix({
        $extend: {
            Record: {
                $buildUrl: function (scope) {
                    return scope.$url();
                }
           }
        }
    });

**Comment by philippeluickx** [comment]
Thanks for that info, interesting approach!

Related question: https://github.com/platanus/angular-restmod/issues/221 - they use $single there which is pretty much undocumented.
