### ISSUE TITLE
Inline Resources with Uri instead of pk

### ISSUE THREAD

**Issue by inferno001** [platanus/angular-restmod#321]
Hello,

I am very new to angular-restmod (coming from restangular) and I am searching for a way to fetch a resource by uri instead of pk.

resource:
```
{
    pk: 1,
    propertyX: 'X', 
    other_resource: '/api/v1/other_resource/1/'
}
```

Now, I want to be able to call something like:
```
resource.$find(1).other_resource.$fetch();
```

I tried to get this working with belongsTo or hasOne. But did not find a proper way.

Maybe there is a way and I am only blind :)

**Comment by ldlsegovia** [comment]
@inferno001 this behaviour is not supported. How do you think this should work?
