### ISSUE TITLE
Cant $fetch if resource is not bound

### ISSUE THREAD

**Issue by scriby** [platanus/angular-restmod#330]
I'm running into a strange instance where I am getting the `Cant $fetch if resource is not bound` error. I know in general this error occurs when trying to $fetch an object which doesn't have its $pk set, but that is not the case this time.

I have a model which has a hasOne relationship. I load the relationship using $fetch, which works fine. Then, later on, I $fetch the relationship again to reload it (I have also tried $refresh).

The second $fetch fails with the above error. Debugging into it a bit, I see some differences from the first $fetch, where it works:

* In the first $fetch call, $url calls $fetchUrlFor. In the second call where it doesn't work, $fetchUrlFor does not exist, and it calls $urlFor.
* In the second call where it doesn't work, $urlFor ends up calling $buildUrl, which calls $url, but $url returns undefined because _baseUrl is not set.
* Also, the relationship object seems to have a $pk defined (like id_1) after the first call. I assume restmod is assigning this, but not really sure where it comes from.

Is any of this making sense? Does it sound like a bug, or does it look like we're doing something wrong?

Thanks,

Chris

**Comment by ldeboer** [comment]
I'm having the same or similar issue!  One thing I noticed is that, for me, the second time I $fetch a resource, it doesn't unpack the results from the "response" object and throws that `Cant $fetch if resource is not bound` error.  This issue also seems to arise when I am using the "shared-restmod" style.  Anyone have thoughts on what's causing this?

**Comment by scriby** [comment]
This turned out to be an issue in our code. We had written a custom method to load the relationship, and it was using $buildRaw instead of $unwrap to populate the object (I just hadn't found that code when I entered the bug report).
