### ISSUE TITLE
Setting partial URL on hasMany relations

### ISSUE THREAD

**Issue by kand** [platanus/angular-restmod#331]
I'm unable to change the partial URL on a ```hasMany``` relationship my model has.

```javascript
angular.module('api.bike', [
  'api.part',
  'restmod'
])
  .factory('Bike', [
    'restmod',
    function (restmod) {

      return restmod.model('bike').mix({
        $config: {
          primaryKey: 'id'
        },
        parts: {
          hasMany: 'Part',
          map: 'parts_set'
        }
      });
    }]
  );
```

When I call ```bike.parts.$create()``` it makes a ```POST``` request to ```/bike/1/parts```, but I need the request to go to ```/bike/1/part``` (not plural). I see that url building goes through [this function call](https://github.com/platanus/angular-restmod/blob/995019e529322322336f70cba4f7006899d5334a/src/module/extended/builder-relations.js#L78) which selects ```_url || _model.encodeUrlName(_attr)```. Is there some way to set the value of ```_url``` here? Or is there some other way this should be done?

**Comment by kand** [comment]
Figured out at least a partial solution to this:

```javascript
angular.module('api.bike', [
  'api.part',
  'restmod'
])
  .factory('Bike', [
    'restmod',
    function (restmod) {

      return restmod.model('bike').mix({
        $config: {
          primaryKey: 'id'
        },
        parts: {
          hasMany: 'Part',
          map: 'parts_set',
          path: 'part'
        }
      });
    }]
  );
```

By providing ```path``` as a property in the parts object, the url is constructed from there instead of the property name.

I am not able to find this anywhere in the documentation.

**Comment by iobaixas** [comment]
`path` was the proper way, I've just updated the docs with the `hasMany` relation options.

**Comment by kand** [comment]
:+1: thanks, where in the documentation is this?
