### ISSUE TITLE
Parent scope not bound when $add-ing a record to a collection

### ISSUE THREAD

**Issue by maufl** [platanus/angular-restmod#332]
I don't know if this is a bug and I don't know if I understand the problem correctly. Maybe I'm even using restmod wrongly.

I have a model, Document, that hasMany nested DocumentPositions.

    GPXPortal.factory('Document', ['restmod', 'DocumentPosition',
        function(restmod, DocumentPosition) {
       
        var Document = restmod.model('/documents').mix({
            positions: { hasMany: 'DocumentPosition', path: 'positions' },
            createdAt: { encode: 'date' },
            updatedAt: { encode: 'date' }
        });
        return Document;
    }]);

    GPXPortal.factory('DocumentPosition', ['restmod', function(restmod) {
        return restmod.model().mix({
            createdAt: { encode: 'date' },
            updatedAt: { encode: 'date' }
        });
    }]);

Now I try to create new DocumentPositions for a document.

    var documentPosition = DocumentPosition.$build();

This works:

    document.positions.$create(documentPosition);

But this does not:

    document.positions.$add(documentPosition);
    documentPosition.$save();

It fails with: `Cant $create if parent scope is not bound`

Now, I could just use $create, but I'm adding multiple DocumentPositions, and I'm altering existing ones. So I would prefer to just add the new ones, and then in a loop, call $save on all of them. (Even better, automatically save all of them when I save Document).
Is that possible?

I want to be able to create and edit a Document and multiple DocumentPositions and when the user presses submits the changes, save everything.
What is the correct way of creating/altering a model with multiple nested models?

**Comment by ldlsegovia** [comment]
Try to perform `document.positions.$build();` instead of `document.positions.$create();`. Then, you can save them in a loop.
