### ISSUE TITLE
Must select a style, but when selected, stops working as expected

### ISSUE THREAD

**Issue by sikko** [platanus/angular-restmod#334]
So when no style is selected, we get the "No API style base was selected" error message.
But when I select a style, the following code example stops working:

    bike = Bike.$find(1);
    bike.brand = 'Trek';
    bike.$save();

Why? because for some reason, restmod wraps all model properties into model.$response.data property.

Here's an example:
Without a style - Working: http://jsfiddle.net/sikko/5pwx4ew1/
With a style (AMSApi) - Not working: http://jsfiddle.net/sikko/gzy2psLv/ 

I'm confused. Any help would be very much appreciated.
Thanks

**Comment by blackjid** [comment]
You can use this Rootless AMS style... is the same as the AMS but without the root property
https://gist.github.com/blackjid/d1eb60243a62e35c1725

Here is the example
http://jsfiddle.net/2easvyqa/

**Comment by sikko** [comment]
Thanks for your help. Here's what I ended up doing:

    restmodProvider.rebase('DefaultPacker');
    restmodProvider.rebase({
      $config: {
        style: 'MyDjangoStyle',
        urlPrefix: '/api'
      },
      'Model.unpack': function(_resource, _raw) {
        if (_resource.$isCollection) {
          _resource.$metadata = {
            count: _raw.count
          };
          return _raw.results;
        } else {
          return _raw;
        }
      }
    });
