### ISSUE TITLE
SharedModel not unpacking data based on load order

### ISSUE THREAD

**Issue by ldeboer** [platanus/angular-restmod#336]
I'm having an issue related to the SharedModel.  Here's an example:

I have a `/scenes` route and I have `/locations` route.  Every scene has a `location` associated with it via a BelongsTo.  When I load the data in the following order everything loads fine:

```
var locations = LocationsFactory.$search().$then(function(){
   var scenes = ScenesFactory.$search()
});
```
Results:  17 scenes are loaded, 13 scenes are loaded.

**However**, when I swap the load order (e.g. scenes and then locations), I suddenly find that the results are different:
Results:  17 scenes are loaded, but only **7** scenes are loaded.

It appears that only the 7 locations that were _not_ tagged in a scene are loaded into the locations object.  If I bury down into the location's $response.data object, I see that indeed all 13 scenes are returned by the API, but for some reason only those 7 were properly unpacked and linked.

I'm using the SharedModel posted by @jasonayre in #208.  Though I've also tried it with the published SharedModel and get the same results.

This issue is happening across all my different routes. It's really crippling my ability to use the SharedModel because I have a TON of related data.

Any insight or thoughts are greatly appreciated!!

**Comment by iobaixas** [comment]
Could you share your model definitions? I'm struggling to understand the underlying structure.

**Comment by ldeboer** [comment]
Hi @iobaixas,
Since posting this question, I've discovered the source of the issue.  It's actually something wrong within the SharedModel code where it would begin to nest scopes after returning them from the cache.  I will do a pull request to propose my patch.
