### ISSUE TITLE
Setting a primaryKey with a dot won't work

### ISSUE THREAD

**Issue by sikko** [platanus/angular-restmod#337]
Setting the primary key on a nested field (with a dot) doesn't work.
For instance:

    model = restmod.model('/customer').mix({
      $config:{
        primaryKey: 'card.id'
      }
    });

I dug into the code and the problem comes from the InferKey function: https://github.com/platanus/angular-restmod/blob/f663c1f7341e87ad79841026ea7e9d94edf0baa6/src/module/factory.js#L128

The problem is that the function tries to get the property using the array like syntax. In this case it would try to get:

    customer['card.id']

Using this method to access properties would fix the issue: http://stackoverflow.com/a/6906859/603058

What would be the best way to implement this change? create a function in Utils? I'd be happy to help, let me know if I should make a pull-request.

**Comment by iobaixas** [comment]
Currently restmod does not have built in support for nested primary keys, you could override the inferKey method to get this to work, something like:

```javascript
restmodProvider.rebase({
  $extend: {
    "Model.inferKey": function(_raw) {
      // extract primary key from _raw, return undefined if raw does not have a primary key 
    }
  }
});
```

**Comment by sikko** [comment]
Thanks for your reply.
The original inferKey function uses the "**config**" variable.

    inferKey: function(_rawData) {
      if(!_rawData || typeof Utils.getPropByString(_rawData, config.primaryKey) === 'undefined') return null;
      return Utils.getPropByString(_rawData, config.primaryKey);
    }

Any idea on how I can access it in my overwritten function?

**Comment by iobaixas** [comment]
Try using `this.getProperty('primaryKey')`

**Comment by sikko** [comment]
That works now. Thanks :+1:
