### ISSUE TITLE
package.json main file is wrong. Can not browserify

### ISSUE THREAD

**Issue by episodeyang** [platanus/angular-restmod#338]
Hi,

The bower main file is correct: 
```javascript
./dist/angular-restmod-bundle.min.js
```

but the package.json doesn't look right. 

This gives an error when 

```javascript
var restmod = require('angular-restmod')
```

Ge

**Comment by episodeyang** [comment]
Hi, 

I created a PR for this. Would you please have a look?

If the change is not correct please let me know!

Ge

#340

**Comment by iobaixas** [comment]
Thanks @episodeyang, change will be available in next release!

**Comment by episodeyang** [comment]
Thanks a lot!!!
