### ISSUE TITLE
Have an endpoint which returns a single value

### ISSUE THREAD

**Issue by mad0house** [platanus/angular-restmod#345]
Hi,

Trying to get to grips with this framework, have an endpoint which returns a single value on post such as "e1adb336a630ec7a7e7fefeaa23e53f2".

The new version from yesterday throws the exception can not decode object, which is true its not an object. This endpoint comes from Magento 2 at /rest/V1/guest-carts/.

In reality we know it should be retuned something like 
```json
{
  "cart_id":"e1adb336a630ec7a7e7fefeaa23e53f2"
}
```
Will most likely try and fix magneto and issue a pull request there, but is there any way to get $save to ignore this check?

**Comment by iobaixas** [comment]
Yes, we added a check to ensure that `$decode` receives an object. Try adding a hook to the `after-request` event that sanitizes the response, like this:

```javascript
$hooks: {
  'after-request': function(_request) {
    if(typeof _request.data == 'string') _request.data = { id: _request.data };
  } 
```
