### ISSUE TITLE
Style being applied twice

### ISSUE THREAD

**Issue by kand** [platanus/angular-restmod#347]
I have a custom style defined something like so:
```javascript
angular.module('styles', [
  'restmod'
])
  .factory('CustomStyle', function (restmod) {
    return restmod.mixin('DefaultPacker', {
      $config: {
        style: 'CustomStyle'
      },
      $hooks: {
        'before-request': function (_req) {
          if (!_req.url.match(/\/$/)) {
            _req.url += '/';
          }
        }
      }
    });
  });
```

Two different libraries are using this style in different ways. The first library rebases all requests through restmod with this style:
```javascript
angular.module('api', [
  'restmod',
  'styles'
])
  .config(function (restmodProvider) {
      restmodProvider.rebase('CustomStyle', {
        $config: {
          style: 'MyApi'
        }
      });
    });
```

The second library has a model that I want to guarantee uses this style even if someone hasn't rebased their restmod calls, so I use the style in the second library like so:
```javascript
angular.module('library', [
  'restmod',
  'styles'
])
  .factory('SomeModel', function (restmod) {
    var customMixin = restmod.mixin('CustomStyle', {
      ...
    });

   return restmod.model('things').mix(customMixin);
  });
```

Now, if I import and attempt to make a request with the library model in the first project, my ```CustomStyle``` will be called twice in all situations it covers, which in this case is just the ```before-request``` hook.

It seems to me like if you're specifying a mixin by name, why would you want to have this mixin be applied twice? Is there a way to prevent this behavior?

**Comment by iobaixas** [comment]
We allow strings just for injection convenience. Mixins are like ruby modules, every time you include them they will be executed on the target class.

Instead of using rebase, you could use a BaseModel mixin and apply it to every model but the second library ones.
