### ISSUE TITLE
Not working when using browserify, missing 'inflector' provider

### ISSUE THREAD

**Issue by episodeyang** [platanus/angular-restmod#348]
Hi, 

I am using the most recent release 1.1.1, with dependency on angular-inflector 1.2.3.

When using either 
```javascript
var restmod = require('angular-restmod')
```

or 
```javascript
var restmod = require('path/to/angular-restmod-bundle.js')
```

the bundled javascript gives an error message, saying that the app is missing the inflector provider.

similar to #158

**Comment by episodeyang** [comment]
Hi, 

Does anyone has any idea of what the problem is with this? Thanks.

**Comment by episodeyang** [comment]
I tried using 

```javascript
require('angular')'
require('angular-restmod');
require('angular-inflector');
```

but it is still not working.

**Comment by iobaixas** [comment]
Could you replicate the problem JSFiddle?

**Comment by episodeyang** [comment]
Hi @iobaixas,

I think it was a setup issue on my part. It seems to be working now.
