### ISSUE TITLE
Populated relations, what's the proper way to define them? 

### ISSUE THREAD

**Issue by avif** [platanus/angular-restmod#351]
Hi,

I have a use case where I might populate a relationship data at the server
and return it to the client with the populated data on the same field.

My resource definitions:
```javascript
//User
angular.module('test')
.factory('User', function (restmod) {
  return restmod.model('/users').mix({
    projects: {
      hasMany: 'Project',
      keys: 'projects'
    }
  });
});

//Project
angular.module('test')
.factory('Project', function (restmod) {
  return restmod.model('/projects').mix({
    createdBy: {
      belongsTo: 'User',
      map: 'createdBy'
    }
  });
});

//My data structure:
User: {
	id: 'u1',
	name: 'User A',
	projects: ['p1', 'p2']
}

Project: {
	id: 'u1',
	name: 'Project A',
	createdBy: 'u1'
}
```
My server will populated the `createdBy` field when a cretin parameter is attached,
but restmod maps the field wrong and the `$pk` field holds all the data instead of just the "id" field.

I tried this with map: `createdBy` set instead of the key field, and it worked!
but as a result the resource throws an error when the field is not populated (expected an object).

What is the best way to go about this?

**Comment by iobaixas** [comment]
You should use `key: 'createdBy'` instead of `map: 'createdBy'`. `map` is for general property remapping, `key` is a `belongsTo` configuration to change the foreign key location.

I'm working of a relations guide to clarify relation options (#352).

**Comment by jpulec** [comment]
Closing as solved.
