### ISSUE TITLE
Set URL without using restmodProvider.rebase

### ISSUE THREAD

**Issue by kievechua** [platanus/angular-restmod#354]
Now I need to support an app that require to call multiple API, base on user input.
Let say user login with branch a, then the api will call https://api-a.example.com.
If user login with branch b, then the api will call https://api-b.example.com.

Is there a way to change the url after initialize?

**Comment by smajl** [comment]
I accidentally created the same issue https://github.com/platanus/angular-restmod/issues/357 (I was searching for `urlPrefix`)... I have similar use case.

This would add a great flexibility for the API. I hope it will be possible.

**Comment by iobaixas** [comment]
Currently is not possible, it could be done though. Here is an idea:

First create a prefix manager service:

```js
angular.module('my-module').factory('ApiPrefixManager', [function() {
  var prefix = null; 
  return {
    setPrefix: function(_prefix) {
      prefix = _prefix;
    },
    getPrefix: function(_for) { // maybe you could use different prefixes for different models...
      return prefix;
    }
  };
}]);
```

Then make models use the service prefix. Make sure you are not setting the `config.urlPrefix` property!.

```js
angular.module('my-module').factory('MutablePrefix', ['RMUtils', 'ApiPrefixManager', function(Utils, Manager) {
  return {
    'Model.$url': function() {
       var baseUrl = this.$super();
       return Utils.joinUrl(Manager.getPrefix(this), baseUrl);
     }
  }
}]);
```

Finally, to change every model prefix call `ApiPrefixManager.setPrefix`.

**Comment by smajl** [comment]
@iobaixas Works, thx a lot!

**Comment by joseglego** [comment]
It works for me too. But, I think it could work only for small applications. It would be not elegant when you have a lot of models. 

e.g. in HUGE apps, you can have 100+ models. And add the `'Model.url'` section for each model could be not efficient and a lot of unnecessaries lines. @iobaixas

**Comment by smajl** [comment]
@joseglego Well, you really don't need to add `Model.url` everywhere. Just create a mixin and then use it (everywhere). From my project:
```javascript
  ...
  .factory('MutablePrefix', function(RMUtils, ApiManager) {
    'ngInject';
    return {
      'Model.$url': function() {
        const baseUrl = this.$super();
        return RMUtils.joinUrl(ApiManager.getPrefix(), baseUrl);
      }
    };
  })
  ...
```
```javascript
function MyModel(restmod) {
  'ngInject';
  return restmod.model('/x/y/z').mix('MutablePrefix', {
    ...
  });
}
```
