### ISSUE TITLE
Pluginfile shared.js is missing in distribution folder

### ISSUE THREAD

**Issue by sighalt** [platanus/angular-restmod#374]
The file shared.js (SharedModel plugin) is not distributed when you install angular-restmod via a package manager.

e.g.:
```bash
$ bower install angular-restmod
$ find . -name shared.js -type f
$
```

I expect adding an entry for this file to Gruntfile.js would fix the problem.

**Comment by jpulec** [comment]
The shared model plugin isn't actually production ready and has a bug. See #204 for a bit of a description. Closing this for now.
