### ISSUE TITLE
Warning from applying custom style to single model according to docs

### ISSUE THREAD

**Issue by boltmedia** [platanus/angular-restmod#379]
Using the format for applying a style to a single model from [style guide](https://github.com/platanus/angular-restmod/blob/master/docs/guides/styles.md) results in the following warning:

```
Passing mixins and definitions in the model method will be deprecated in restmod 1.2, use restmod.model().mix() instead.
```

**Comment by furqanaziz** [comment]
Previously it was allowed to pass mixins/styles into restmod.model() function while defining our model and it is working fine till now. But this feature is going to be deprecated in future. You can avoid this by replacing 
```
restmod.model('/url', 'amsStyle'); 
```
to 
```
restmod.model('/url').mix('amsStyle'); 
```

Both work in the same way. Hope it makes sense to you. Sorry for the late reply.

**Comment by boltmedia** [comment]
Thanks! All set.
