### ISSUE TITLE
jsonapi.org support

### ISSUE THREAD

**Issue by iobaixas** [platanus/angular-restmod#50]
After object wrapped responses and request are supported it would be nice to support  the http://jsonapi.org/ standard using an extension.

**Comment by jeremy-hunter** [comment]
I am wanting to add jsonapi.org as a style to angular-restmod - any reason not to?

Thank you!

**Comment by rbarilani** [comment]
:+1:

**Comment by philippeluickx** [comment]
@jeremy-hunter did you get anywhere with this? Would be great to have a style for json api!
