### ISSUE TITLE
expose raw http methods in model instances

### ISSUE THREAD

**Issue by jasonayre** [platanus/angular-restmod#70]
Would be nice if the model instances, and classes had a raw $post / $get / $put available, which would post to the endpoint, and run it through whatever sends the data to the packer. (And in the case of the instance method version, it would update itself based on the result from server) -- Im trying to migrate from angularjs-rails-resource as this library seems to have alot of what Ive been wishing it had, but am noticing alot of things Im missing at the same time.

https://github.com/FineLinePrototyping/angularjs-rails-resource
Has more details, but basically, Im trying to do something along the lines of

``` javascript
angular.module('myapp').controller('LoginController', ["$scope", "$state", "CurrentPerson", function($scope, $state, CurrentPerson) {
  $scope.resource = new CurrentPerson();

  $scope.submit = function() {
    $scope.resource.login().then(function(person) {
	  $scope.$root.$broadcast('authorized', person);
    }
  }
}]);
```

**What Id like to be able to do:**

note this is a very specific use case , but my worry is more about working with non standard member or collection actions in general on server side

``` javascript
angular.module('myapp').factory("CurrentPerson", ["BaseModel", "$restmod", "$http", function(BaseModel, $restmod, $http) {
  resource.prototype.login = function() {
	var self = this;
	return this.$post(self.$url('login'), {
	  email: self.email,
	  password: self.password
	});
  };
}]);
```

**What Im having to do**

``` javascript
angular.module('myapp').factory("CurrentPerson", ["BaseModel", "$restmod", "$http", function(BaseModel, $restmod, $http) {
  var model = $restmod.model('/person', BaseModel, {
    login: function() {
      var self = this;

      return $http.post(self.$scope.$urlFor('login'), {
        email: self.email,
        password: self.password
      });
    },
    logout: function() {
      return $localForage.clearAll();
    }
  });

  model.collection_key = 'people';
  model.resource_key = 'person';

  return model;
}]);
```

Point is, it would be nice to have $post post to the collection or member action, return the new data from the server, and replace the current instance with a new instance of self, transforming the attributes by passing it through the packer -- Which may or may not be easy with the architecture of the library, I know Angular rails resource uses interceptors, and then tries to deserialize if it detects a valid root json key, so its probably far diff than the pack/unpack response structure.

**Comment by hinok** [comment]
Could someone explain why did you use `this.$action()` here? I'm not sure but I think that using just `this.$send` should also work.

I'm asking because in closed issue: https://github.com/platanus/angular-restmod/issues/106, `this.$send()` is using without `this.$action()`

**Comment by iobaixas** [comment]
@hinok, wrapping stuff as `$action` lets you cancel if it gets queued after other actions.

I'm closing this issue since we are not giving support for non-restful actions.  I think that if you really need custom action then using `$send` + `$unwrap` is enough. 

I'll gladly accept a PR for a raw http methods extension though.
